[[cells]]
name = "spore"
enable_type_id = false
location = { file = "binSpore" }

[[cells]]
name = "cluster"
enable_type_id = false
location = { file = "binCluster" }

[[cells]]
name = "auth"
enable_type_id = false
location = { file = "../../build/auth" }

[[cells]]
name = "transaction-cobuild-lock-demo"
enable_type_id = false
location = { file = "../../build/release/transaction-cobuild-lock-demo" }

# The lock script set to output cells
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x0000000000000000000000000000000000000000"
hash_type = "type"
