# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.10.2 5e49142"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "transaction-cobuild-lock-demo"
template_type = "Rust"

[[contracts]]
name = "transaction-cobuild-type-demo"
template_type = "Rust"

[[contracts]]
name = "transaction-cobuild-otx-lock-demo"
template_type = "Rust"

[[contracts]]
name = "always-success"
template_type = "Rust"
